name: WonderHaul
main: io.github.winterbear.wintercore.WonderHaul
version: 2.0
api-version: 1.13
commands: 
  getTag:
    permission: taggenerator.gettag
  generateItem:
    permission: itemgenerator.test
  setHealth:
    permission: dev.sethealth
  setHunger:
    permission: dev.sethunger
  addLore:
    permission: dev.addlore
  clearLore:
    permission: dev.clearLore
  removeLore:
    permission: dev.removelore
